version: '3.8'

services:
  web:
    build: ./carzlayout
    command: gunicorn carzlayout.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./carzlayout:/PLACEMENT
      - static_volume:/PLACEMENT/static
      - media_volume:/PLACEMENT/media
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static_volume:/PLACEMENT/static
      - media_volume:/PLACEMENT/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
