# Generated by Django 5.0.1 on 2024-01-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['-time_create'], name='cars_car_time_cr_b3586b_idx'),
        ),
    ]
