# Generated by Django 5.0.1 on 2024-01-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
