# Generated by Django 5.0.1 on 2024-01-31 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_category_car_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cars.category'),
            preserve_default=False,
        ),
    ]
