# Generated by Django 5.0.1 on 2024-02-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_company_mine_shaft_yearmonth_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shaft',
            name='mine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.mine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='shaft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.shaft'),
            preserve_default=False,
        ),
    ]
