# Generated by Django 5.0.1 on 2024-02-06 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_shaft_mine_site_shaft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shaft',
            name='mine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.mine'),
        ),
        migrations.AlterField(
            model_name='site',
            name='shaft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cars.shaft'),
        ),
    ]
