# Generated by Django 5.0.1 on 2024-02-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_shaft_mine_alter_site_shaft'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearmonth',
            name='month',
            field=models.IntegerField(choices=[(0, 'Год'), (1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], default=0),
        ),
    ]
