# Generated by Django 5.0.1 on 2024-02-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mine',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shaft',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
