# Generated by Django 5.0.1 on 2024-02-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_mine_slug_shaft_slug_site_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_zadanie',
            name='site',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mine',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Рудник'),
        ),
        migrations.AlterField(
            model_name='shaft',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Шахта'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Участок'),
        ),
    ]
