# Generated by Django 5.0.1 on 2024-02-19 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_historicalplan_zadanie_changed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_zadanie',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site'),
        ),
    ]
