# Generated by Django 5.0.1 on 2024-02-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_alter_plan_zadanie_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplan_zadanie',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='plan_zadanie',
            name='updated',
        ),
    ]
