# Generated by Django 5.0.1 on 2024-02-23 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_historicalnsmen_historicalplotnost_gruza_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplan_zadanie',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalplan_zadanie',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalplan_zadanie',
            name='period',
        ),
        migrations.RemoveField(
            model_name='historicalplan_zadanie',
            name='site',
        ),
        migrations.RemoveField(
            model_name='historicalplotnost_gruza',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalplotnost_gruza',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalplotnost_gruza',
            name='period',
        ),
        migrations.RemoveField(
            model_name='historicalplotnost_gruza',
            name='site',
        ),
        migrations.RemoveField(
            model_name='historicalschema_otkatki',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalschema_otkatki',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalschema_otkatki',
            name='period',
        ),
        migrations.RemoveField(
            model_name='historicalschema_otkatki',
            name='site',
        ),
        migrations.RemoveField(
            model_name='historicalt_pereezd',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalt_pereezd',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalt_pereezd',
            name='period',
        ),
        migrations.RemoveField(
            model_name='historicalt_pereezd',
            name='site',
        ),
        migrations.RemoveField(
            model_name='historicalt_regl_pereryv',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalt_regl_pereryv',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalt_regl_pereryv',
            name='period',
        ),
        migrations.RemoveField(
            model_name='historicalt_regl_pereryv',
            name='site',
        ),
        migrations.RemoveField(
            model_name='historicalt_smeny',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalt_smeny',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalt_smeny',
            name='period',
        ),
        migrations.RemoveField(
            model_name='historicalt_smeny',
            name='site',
        ),
        migrations.RemoveField(
            model_name='historicalt_vspom',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalt_vspom',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalt_vspom',
            name='period',
        ),
        migrations.RemoveField(
            model_name='historicalt_vspom',
            name='site',
        ),
        migrations.AddField(
            model_name='nsmen',
            name='document',
            field=models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование'),
        ),
        migrations.AddField(
            model_name='plan_zadanie',
            name='document',
            field=models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование'),
        ),
        migrations.AddField(
            model_name='plotnost_gruza',
            name='document',
            field=models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование'),
        ),
        migrations.AddField(
            model_name='schema_otkatki',
            name='document',
            field=models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование'),
        ),
        migrations.AddField(
            model_name='t_pereezd',
            name='document',
            field=models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование'),
        ),
        migrations.AddField(
            model_name='t_regl_pereryv',
            name='document',
            field=models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование'),
        ),
        migrations.AddField(
            model_name='t_smeny',
            name='document',
            field=models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование'),
        ),
        migrations.AddField(
            model_name='t_vspom',
            name='document',
            field=models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование'),
        ),
        migrations.AlterField(
            model_name='nsmen',
            name='Nsm',
            field=models.FloatField(verbose_name='Количество смен'),
        ),
        migrations.AlterField(
            model_name='nsmen',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='nsmen',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления'),
        ),
        migrations.AlterField(
            model_name='nsmen',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='nsmen',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='plan_zadanie',
            name='Qpl',
            field=models.FloatField(verbose_name='План задание'),
        ),
        migrations.AlterField(
            model_name='plan_zadanie',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='plan_zadanie',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления'),
        ),
        migrations.AlterField(
            model_name='plan_zadanie',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='plan_zadanie',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='plotnost_gruza',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='plotnost_gruza',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления'),
        ),
        migrations.AlterField(
            model_name='plotnost_gruza',
            name='d',
            field=models.FloatField(verbose_name='Плотность груза'),
        ),
        migrations.AlterField(
            model_name='plotnost_gruza',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='plotnost_gruza',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='schema_otkatki',
            name='L',
            field=models.FloatField(verbose_name='Плечо откатки'),
        ),
        migrations.AlterField(
            model_name='schema_otkatki',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='schema_otkatki',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления'),
        ),
        migrations.AlterField(
            model_name='schema_otkatki',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='schema_otkatki',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='t_pereezd',
            name='Tprz',
            field=models.FloatField(verbose_name='Время переезда'),
        ),
        migrations.AlterField(
            model_name='t_pereezd',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='t_pereezd',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления'),
        ),
        migrations.AlterField(
            model_name='t_pereezd',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='t_pereezd',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='t_regl_pereryv',
            name='Tregl',
            field=models.FloatField(verbose_name='Регламентные перерывы'),
        ),
        migrations.AlterField(
            model_name='t_regl_pereryv',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='t_regl_pereryv',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления'),
        ),
        migrations.AlterField(
            model_name='t_regl_pereryv',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='t_regl_pereryv',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='t_smeny',
            name='Tsm',
            field=models.FloatField(verbose_name='Длительность смены'),
        ),
        migrations.AlterField(
            model_name='t_smeny',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='t_smeny',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления'),
        ),
        migrations.AlterField(
            model_name='t_smeny',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='t_smeny',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='t_vspom',
            name='Tvsp',
            field=models.FloatField(verbose_name='Вспомогательное время'),
        ),
        migrations.AlterField(
            model_name='t_vspom',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='t_vspom',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления'),
        ),
        migrations.AlterField(
            model_name='t_vspom',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='t_vspom',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок'),
        ),
        migrations.DeleteModel(
            name='HistoricalNsmen',
        ),
        migrations.DeleteModel(
            name='HistoricalPlan_zadanie',
        ),
        migrations.DeleteModel(
            name='HistoricalPlotnost_gruza',
        ),
        migrations.DeleteModel(
            name='HistoricalSchema_otkatki',
        ),
        migrations.DeleteModel(
            name='HistoricalT_pereezd',
        ),
        migrations.DeleteModel(
            name='HistoricalT_regl_pereryv',
        ),
        migrations.DeleteModel(
            name='HistoricalT_smeny',
        ),
        migrations.DeleteModel(
            name='HistoricalT_vspom',
        ),
    ]
