# Generated by Django 5.0.1 on 2024-02-28 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_remove_historicalplan_zadanie_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nsmen',
            options={'verbose_name': 'Nsm - Количество смен'},
        ),
        migrations.AlterModelOptions(
            name='plan_zadanie',
            options={'verbose_name': 'Qpl - План задание'},
        ),
        migrations.AlterModelOptions(
            name='plotnost_gruza',
            options={'verbose_name': 'd - Плотность груза'},
        ),
        migrations.AlterModelOptions(
            name='schema_otkatki',
            options={'verbose_name': 'L - Плечо откатки'},
        ),
        migrations.AlterModelOptions(
            name='t_pereezd',
            options={'verbose_name': 'Tprz - Время переезда'},
        ),
        migrations.AlterModelOptions(
            name='t_regl_pereryv',
            options={'verbose_name': 'Tregl - Регламентные перерывы'},
        ),
        migrations.AlterModelOptions(
            name='t_smeny',
            options={'verbose_name': 'Tsm - Длительность смены'},
        ),
        migrations.AlterModelOptions(
            name='t_vspom',
            options={'verbose_name': 'Tvsp - Вспомогательное время'},
        ),
        migrations.CreateModel(
            name='Kuzov_Coeff_Zapl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления')),
                ('document', models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование')),
                ('Kz', models.FloatField(verbose_name='Коэффициент заполнения кузова')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Kz - Коэффициент заполнения кузова',
            },
        ),
        migrations.CreateModel(
            name='T_pogruzki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления')),
                ('document', models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование')),
                ('Tpogr', models.FloatField(verbose_name='Продолжит погрузки со сменой автосам')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Tpogr - Продолжит погрузки со сменой автосам',
            },
        ),
        migrations.CreateModel(
            name='T_razgruzki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления')),
                ('document', models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование')),
                ('Trazgr', models.FloatField(verbose_name='Прожолжит. разгрузки с маневрами')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Trazgr - Прожолжит. разгрузки с маневрами',
            },
        ),
        migrations.CreateModel(
            name='V_objem_kuzova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления')),
                ('document', models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование')),
                ('Vk', models.FloatField(verbose_name='Объем кузова')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Vk - Объем кузова',
            },
        ),
        migrations.CreateModel(
            name='V_Skorost_dvizh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата_обновления')),
                ('document', models.FileField(null=True, upload_to='property_documents/', verbose_name='Документ_обоснование')),
                ('Vdv', models.FloatField(verbose_name='Средн. скорость движения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.yearmonth', verbose_name='Период')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Vdv - Средн. скорость движения',
            },
        ),
    ]
