# Generated by Django 5.0.1 on 2024-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_alter_nsmen_options_alter_plan_zadanie_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='KTG',
            field=models.FloatField(blank=True, null=True, verbose_name='КТГ'),
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='KTG',
            field=models.FloatField(blank=True, null=True, verbose_name='КТГ'),
        ),
    ]
