# Generated by Django 5.0.1 on 2024-02-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_car_ktg_historicalcar_ktg'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='V_objem_kuzova',
            field=models.FloatField(blank=True, null=True, verbose_name='Емкость кузова с шапкой'),
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='V_objem_kuzova',
            field=models.FloatField(blank=True, null=True, verbose_name='Емкость кузова с шапкой'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.category', verbose_name='Категория'),
        ),
    ]
