# Generated by Django 5.0.1 on 2024-02-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_car_v_objem_kuzova_historicalcar_v_objem_kuzova_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='KTG',
        ),
        migrations.RemoveField(
            model_name='historicalcar',
            name='KTG',
        ),
    ]
