# Generated by Django 5.0.1 on 2024-03-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0030_ktg_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuzov_coeff_zapl',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='nsmen',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='plan_zadanie',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='plotnost_gruza',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='schema_otkatki',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='t_pereezd',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='t_pogruzki',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='t_razgruzki',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='t_regl_pereryv',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='t_smeny',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='t_vspom',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='v_objem_kuzova',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
        migrations.AddField(
            model_name='v_skorost_dvizh',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение'),
        ),
    ]
