# Generated by Django 5.0.1 on 2024-03-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_kuzov_coeff_zapl_value_nsmen_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kuzov_coeff_zapl',
            name='Kz',
        ),
        migrations.RemoveField(
            model_name='nsmen',
            name='Nsm',
        ),
        migrations.RemoveField(
            model_name='plan_zadanie',
            name='Qpl',
        ),
        migrations.RemoveField(
            model_name='plotnost_gruza',
            name='d',
        ),
        migrations.RemoveField(
            model_name='schema_otkatki',
            name='L',
        ),
        migrations.RemoveField(
            model_name='t_pereezd',
            name='Tprz',
        ),
        migrations.RemoveField(
            model_name='t_pogruzki',
            name='Tpogr',
        ),
        migrations.RemoveField(
            model_name='t_razgruzki',
            name='Trazgr',
        ),
        migrations.RemoveField(
            model_name='t_regl_pereryv',
            name='Tregl',
        ),
        migrations.RemoveField(
            model_name='t_smeny',
            name='Tsm',
        ),
        migrations.RemoveField(
            model_name='t_vspom',
            name='Tvsp',
        ),
        migrations.RemoveField(
            model_name='v_objem_kuzova',
            name='Vk',
        ),
        migrations.RemoveField(
            model_name='v_skorost_dvizh',
            name='Vdv',
        ),
        migrations.AlterField(
            model_name='kuzov_coeff_zapl',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='nsmen',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='plan_zadanie',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='plotnost_gruza',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='schema_otkatki',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='t_pereezd',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='t_pogruzki',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='t_razgruzki',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='t_regl_pereryv',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='t_smeny',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='t_vspom',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='v_objem_kuzova',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='v_skorost_dvizh',
            name='value',
            field=models.FloatField(null=True, verbose_name='Значение'),
        ),
    ]
