# Generated by Django 5.0.1 on 2024-03-11 08:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0032_remove_kuzov_coeff_zapl_kz_remove_nsmen_nsm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlacement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cars.site', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'historical Размещение',
                'verbose_name_plural': 'historical Размещения',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.site', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Размещение',
                'verbose_name_plural': 'Размещения',
            },
        ),
        migrations.CreateModel(
            name='PlacementCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Машина')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.placement', verbose_name='Размещение')),
            ],
            options={
                'verbose_name': 'Размещенные машины',
                'verbose_name_plural': 'Размещенные машины',
            },
        ),
        migrations.AddField(
            model_name='placement',
            name='cars',
            field=models.ManyToManyField(through='cars.PlacementCar', to='cars.car', verbose_name='Машины'),
        ),
    ]
