# Generated by Django 5.0.1 on 2024-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0034_historicalplacement_period_placement_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='artikul',
            field=models.CharField(max_length=13, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='car',
            name='garnom',
            field=models.CharField(max_length=6, null=True, verbose_name='Гаражный номер'),
        ),
        migrations.AddField(
            model_name='car',
            name='vvod',
            field=models.DateTimeField(null=True, verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='artikul',
            field=models.CharField(max_length=13, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='garnom',
            field=models.CharField(max_length=6, null=True, verbose_name='Гаражный номер'),
        ),
        migrations.AddField(
            model_name='historicalcar',
            name='vvod',
            field=models.DateTimeField(null=True, verbose_name='Дата ввода в эксплуатацию'),
        ),
    ]
