# Generated by Django 5.0.1 on 2024-03-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0035_car_artikul_car_garnom_car_vvod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='tags',
        ),
    ]
