# Generated by Django 5.0.1 on 2024-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0036_remove_car_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='artikul',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='historicalcar',
            name='artikul',
            field=models.CharField(db_index=True, max_length=13, null=True, verbose_name='Артикул'),
        ),
    ]
