# Generated by Django 5.0.1 on 2024-03-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0038_alter_t_razgruzki_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='V_objem_kuzova',
        ),
    ]
