# Generated by Django 5.0.1 on 2024-03-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0039_delete_v_objem_kuzova'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplacement',
            name='calculations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='historicalplacement',
            name='nspis',
            field=models.FloatField(default=0.0, verbose_name='Принятое списочное кол-во машин'),
        ),
        migrations.AddField(
            model_name='placement',
            name='calculations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='placement',
            name='nspis',
            field=models.FloatField(default=0.0, verbose_name='Принятое списочное кол-во машин'),
        ),
    ]
